name: ci

on:
  push:
    branches: [main, dev]
  # pull_request:
  #   breaches: [main, dev]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ls -alF
        run: |
          ls -alF
          pwd
          mkdir -p ~/artifact
          echo hello > ~/artifact/world.txt
      - name: upload files
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: |
            ~/artifact/world.txt
